### ISSUE TITLE
Create a generic spectator view prefab that supports all localization scenarios

### ISSUE THREAD

**Issue by chrisfromwork** [microsoft/MixedReality-SpectatorView#10]

**Comment by chrisfromwork** [comment]
This work should only encompass getting a prefab together with marker-based localization as the default for mobile. Future tasks will be opened to enabling editing of the default localizer.

**Comment by matthejo** [comment]
One of the challenges with a single prefab is how to configure app-specific settings. Here's a proposal for how to allow this:

1. The SpectatorView script will try to instantiate a prefab named SpectatorViewSettings.prefab from resources. The "Spectator View" menu in Unity will automatically create such a prefab if it does not exist in the correct Resources subfolder.
2. The SpectatorViewSettings prefab can contain a number of app-specific settings
 * Settings for state synchronization broadcasting (BroadcasterSettings)
 * Choice of which type of SpatialLocalizer to use by default
 * Localization settings for the SpatialLocalizer
 * IP address of the device to connect to

Keeping app-specific settings in a prefab avoids the need for apps to modify the values in the SpectatorView prefab itself. This will make it easier to avoid merge conflicts when getting new versions of the prefab, and avoids accidentally applying prefab values from an app scene into the SpectatorView prefab.

For localization, I'm proposing the following flow:
1. When connecting to a HoloLens, the HoloLens will communicate the list of supported ISpatialLocalizers over the network. This can then be cached inside the SpatialCoordinateSystemParticipant
2. When a LocalizationInitializer is ready to begin localization, it will use the list of supported remote localizers to choose which localization type to initiate.
