### ISSUE TITLE
Suggestions for Basic Setup List

### ISSUE THREAD

**Issue by Railboy** [microsoft/MixedReality-SpectatorView#113]
The docs are fantastic on the whole. Based on my first experience with your Basic Setup List, I have some suggestions.

First, I'd suggest breaking the list into 2 sections, Setup and Build.

> ### Setup
> ~~1. Ensure you have all of the Software & Hardware.~~
>~~- Ensure you have added the appropriate platform dependencies to your project (ARCore/ARKit)~~

Step 1 is conceptual overload. Dependencies are brought up in a more appropriate step later.

> ~~2.~~ 1. Download the Spectator View repository.
> ~~3.~~ 2. Copy the contents of src\SpectatorView.Unity\Assets to MixedReality.SpectatorView folder in the Assets folder of your project.
> ~~4.~~ 3. Add the MixedReality.SpectatorView/SpectatorView/Prefabs/SpectatorView.prefab prefab to your primary scene.

Adding the prefab should be the first step you take in a new project. The prefab will provide context for the following steps & concepts.

> ~~5.~~ 4. Choose a Spatial Alignment Strategy and spatial localizer.

This step introduces the concept of a **Spatial Alignment Strategy.** The linked Spatial Alignment doc doesn't provide a concise description of a strategy or concrete steps for selecting one. Suggestion for Spatial Alignment doc introduction:

_There are different ways to align your content with the world. We call these Spatial Alignment Strategies. Which strategy you choose will depend on your platform, the capabilities of your devices and the goals of your app. You select your strategy by [insert concrete steps or link directly to Setup page]._

> ~~6.~~ 5. Add the appropriate Spatial Localizer Dependencies based on your chosen spatial localizer.

There's no connective language linking **Spatial Alignment Strategy** to **Spatial Alignment Localizer**. So when the next step asks us to add dependencies for a localizer there's a conceptual disconnect.

> ~~7. Configure the localization methods you wish to use: Spatial Localizer Dependencies.~~ 
> 6. Download the dependencies required by your chosen strategy: Spatial Localizer Dependencies

Configure gives the impression that I will be configuring the prefab but that's not what we're doing here.

The remaining steps should be separated into a separate list called **Build**. They won't be relevant for a long time while folks get their project set up.

>### Build
>  ~~8.~~ 1. Generate and check-in Asset Caches to your project repo: Before Building

This step introduces the concept of **Asset Caches.** The Before Building doc only has a side note that already assumes an understanding of what they are. This step should link to a brief doc explaining what they are and why they need to be generated.

> ~~10.~~ 2. Configure the IP Address of the host device in the spectating scene for each platform MixedReality.SpectatorView/SpectatorView/SpectatorView.<Platform>.unity you will deploy to.
> ~~9.~~ 3. Build & Deploy your primary scene onto the hosting device.
> ~~11.~~ 4. Build & Deploy your spectating scenes onto the spectating devices.

Moving back and forth between configuration and deployment is jarring so I would re-order those steps.

Also, concepts like **Primary Scene**, **Spectating Scene**, **Hosting Device** and **Spectating Device** have not been introduced yet. In the Setup list, I'd suggest adding two final steps:

> 7. Create a Primary Scene for your Hosting Device: [Link to scene and device setup doc]
> 8. Create a Spectating Scene for your Spectating Devices: [Link to scene and device setup doc]

Lastly, please mention the SpectatorView prefab more often. For most people this will be the object that their thoughts are organized around, and it's barely mentioned. For instance:

> Set the User IP Address on the Spectator View script to the ip address of your HoloLens device.

> **Select the SpectatorView prefab and** set the User IP Address on the Spectator View script to the ip address of your HoloLens device.

**Comment by chrisfromwork** [comment]
This is great feedback, I'll label this issue as an item to address for 8.15
