### ISSUE TITLE
SpectatorView videos hard to find and won't play on Android

### ISSUE THREAD

**Issue by grbury** [microsoft/MixedReality-SpectatorView#122]
The recorded videos on Android save to a root location on the SD card, which is terrible hard to find - it was by chance that I saw them in the Samsung Files app.  They would Ideally appear in a videos folder named with "Spectator View".

Also, tapping the videos and trying to open in Android's video player failed to play the recorded videos.

**Comment by chrisfromwork** [comment]
@grbury one follow up question, did you ever try and play the videos on a different device?

**Comment by grbury** [comment]
Yes - they would play on PC, only fail playing on Android phone directly.

**Comment by chrisfromwork** [comment]
This needs to still be investigated. It's unclear whether the video playback error will occur on other devices.
