### ISSUE TITLE
SpectatorView.WinRTExtensions plugin failed

### ISSUE THREAD

**Issue by blcx2211071** [microsoft/MixedReality-SpectatorView#134]
When the iphone  connect to the hololens server。 showing "Call to the SpectatorView.WinRTExtensions plugin failed. The plugin is required for correct behavior when using .NET Native compilation" on hololens。But，anything goes well，also can show QRcode，can show cube is rotating and synchronize well。 What did i do wrong?  Please!  Thank you!

**Comment by matthejo** [comment]
It sounds like you may not have built the SpectatorView.WinRTExtensions.dll, which is built from the SpectatorView.Native project, or may have not copied that DLL into your Unity project. There are instructions [here](https://github.com/microsoft/MixedReality-SpectatorView/blob/master/src/SpectatorView.Native/README.md) for building and installing the plugin. Note that if you don't want to build the entire SpectatorView.Native solution, you can build only the SpectatorView.WinRTExtensions project within the solution.

Note that this error will only be a problem when doing QR code or ArUco marker detection on "Master" build configurations. Everything will still work as expected on "Debug" or "Release" build configurations, so that may explain why everything is still working on your current configuration.

**Comment by blcx2211071** [comment]
> It sounds like you may not have built the SpectatorView.WinRTExtensions.dll, which is built from the SpectatorView.Native project, or may have not copied that DLL into your Unity project. There are instructions [here](https://github.com/microsoft/MixedReality-SpectatorView/blob/master/src/SpectatorView.Native/README.md) for building and installing the plugin. Note that if you don't want to build the entire SpectatorView.Native solution, you can build only the SpectatorView.WinRTExtensions project within the solution.
> 
> Note that this error will only be a problem when doing QR code or ArUco marker detection on "Master" build configurations. Everything will still work as expected on "Debug" or "Release" build configurations, so that may explain why everything is still working on your current configuration.

**Comment by blcx2211071** [comment]
I have already built the SpectatorView.WinRTExtensions.dll for X86 and copied that DLL into my Unity project. I tried many times, but all show that error.  And thank you!

**Comment by chrisfromwork** [comment]
@blcx2211071 a few additional questions:

1) Are you using a HoloLens or HoloLens 2?
2) Did you use the tools\Scripts\CopyPluginsToUnity.bat script to add the dll to your project? If not, did you put the SpectatorView.WinRTExtensions.dll into a Assets\Plugins\WSA\x86 directory (Assets\Plugins\WSA\arm for HoloLens 2)?
3) After you generated your visual studio solution, did the SpectatorView.WinRTExtensions.dll appear in the visual studio solution explorer? Sometimes if a dll is added to a Unity project after you have already generated a visual studio project, things don't get picked up correctly. If this dll isn't appearing in the visual studio solution folder/visual studio solution explorer, you can try deleting this sln/vcxproj directory and recreating.

**Comment by blcx2211071** [comment]
@chrisfromwork
I am using a Hololens. I am sure that i dit anything what you teach me. But that error is still occur. It drives me crazy.  Is it related to the windowsSDK ？  I  modified the building target platform, is 10.0.18362.0，and the lowest is 10.0.17763.0.  And thank you very much!

**Comment by chrisfromwork** [comment]
![Screenshot (15)](https://user-images.githubusercontent.com/10225640/61910189-c3ac3780-aee8-11e9-8a00-d5a71ea40971.png)

When you look at the visual studio project that Unity generated, do you see SpectatorView.WinRTExtensions.dll declared in the project (see above)? Also, are you building with il2cpp or .NET?

**Comment by blcx2211071** [comment]
![20190726091514](https://user-images.githubusercontent.com/30484689/61919062-8b5b3680-af86-11e9-8d50-27374be73f19.png)
The SpectatorView.WinRTExtensions.dll is existed. I built with il2cpp.

**Comment by chrisfromwork** [comment]
Thank you for filing this issue, I was able to repro the problem locally in il2cpp builds. It appears that for il2cpp configurations a MarshalDirectiveException occurs. The WinRTExtensions dll is only needed for .Net native builds, so we are going to only call into it for .NET builds. The review here should fix the issue you are seeing: https://github.com/microsoft/MixedReality-SpectatorView/pull/159
