### ISSUE TITLE
mainTemplate.gradle required for ASA in custom project

### ISSUE THREAD

**Issue by BastiaanGrisel** [microsoft/MixedReality-SpectatorView#182]
I could not get the Azure Cloud Anchors to work in my own project, the objects would replicate from HL1 to my Android phone but the positions would not be synced. The alignment only worked after copying the `mainTemplate.gradle` file found in the BUILD2019 sample to `Assets/Plugins/Android` of my new project. I tried removing the `mainTemplate.gradle` file and it broke the alignment and when adding it again it worked. 

I don't know if this is some edge case on my machine (I don't think so) but I thought I'd mention it here.

**Comment by BastiaanGrisel** [comment]
Putting it in the docs would be great. I don't know which section it should be in since the file was definitely needed for ASA to work. Other than that, so far so good, though I am yet to add spectator mode to an existing project with multiple scenes.

**Comment by chrisfromwork** [comment]
The first wave of fixing htis has been introduced with https://github.com/microsoft/MixedReality-SpectatorView/pull/227

AddDependencies.bat now includes Android plugin directory that contains the gradle file. I am going to also add this to our troubleshooting instructions.
