### ISSUE TITLE
Build2019Demo项目发布

### ISSUE THREAD

**Issue by RenSiyao** [microsoft/MixedReality-SpectatorView#191]
我没有按照正常的拉取操作从Git上格隆项目（只是依赖部分，因为依赖部分通过控制台克隆一直失败）将所有依赖包手动添加完成后，尝试使用Unity 2018.3.14F1发布

- ![`N5T 37NTG(22W4@SO~278N](https://user-images.githubusercontent.com/53859046/63398350-ddfe0600-c3ff-11e9-8168-c1f75fcbb845.png)

虽然报错但是以成功完成构建

- ![`N{D528~ DVWKKTAHPA)V E](https://user-images.githubusercontent.com/53859046/63398387-fa01a780-c3ff-11e9-9924-b7d5d5e7f088.png)

接着我继续使用VS 编译，试图发布运行 ，但是我遇到了问题，看起像是丢失某些库文件。

- 
![U_}2Y$COGBKG8W3Z22UUIBK](https://user-images.githubusercontent.com/53859046/63398667-e276ee80-c400-11e9-9bb9-778bab50d95c.png)

希望有遇到类似问题的帮忙解答，或者告诉我正确的操作方式。谢谢。

**Comment by RenSiyao** [comment]
I find it seems that the questions need to be submitted in English.
I don't have, in accordance with the normal from the Git pull operation, long project (just rely on part because depend on the section through the console cloning has been failure) will all depend on the package manually add finished, try using the Unity 2018.3.14 F1, although an error to the successful completion of the building, and then continue to use VS I compile, tried to run, but I met a problem, look like a lost some library files.
I hope you can help me solve similar problems or tell me the correct way to operate.thank you

**Comment by chrisfromwork** [comment]
If things compiled correctly in visual studio, I believe you are in good shape to get things working. These EnumerateFaceTrackingVideoFormats and UnityARVideoFormat errors don't seem like things that would be related to the HoloLens codebase.

Did you obtain ARKit dependencies and add them to your project? If so, try deleting the content in the ARKitUnityPlugin folder and recompile. ARKit scripts don't play well with hololens/you should only add them when you are working on a mac to build the iOS application. I typically build with .NET, which I think causes this to appear as an error in Unity prior to compiling in visual studio.

If ARKitUnityPlugin does not contain the ARKit dependencies, let us know. Also, what commit/branch are you using to build this project?

**Comment by RenSiyao** [comment]
> 如果在visual studio中正确编译了一些东西，我相信你能够很好地完成工作。这些EnumerateFaceTrackingVideoFormats和UnityARVideoFormat错误似乎与HoloLens代码库有关。
> 
> 您是否获得了ARKit依赖项并将它们添加到您的项目中？如果是这样，请尝试删除ARKitUnityPlugin文件夹中的内容并重新编译。ARKit脚本与hololens不兼容/你应该只在你使用mac来构建iOS应用程序时添加它们。我通常使用.NET构建，我认为在Visual Studio中编译之前，这会导致它在Unity中出现错误。
> 
> 如果ARKitUnityPlugin不包含ARKit依赖项，请告诉我们。另外，您使用什么提交/分支来构建此项目？


I have solved the last problem. Thanks for your reply. I use the main branch.However, I am now Posting spectatorview. HoloLens to my Hololens1, and some opencv. DLL libraries are reporting errors, I don't know what the problem is
=========================================================
=======================Here is my project Log===================
=========================================================
Loading native plugins
  Loading AudioPluginMsHRTF.dll
Module information:
 Built with Compiler Ver '191326128'
 Built from '2018.4/staging' branch
 Version is '2018.4.5f1 (7b38f8ac282e)'
 Release build
 Application type 'D3D'
 OS 'Windows 10 (10.0.17763)'
PlayerConnection initialized from C:/Data/Programs/WindowsApps/Template3D_1.0.0.0_x86__ph1m9x8skttmg/Data (debug = 0)
PlayerConnection initialized network socket : 0.0.0.0 55427
Multi-casting "[IP] 192.168.1.163 [Port] 55427 [Flags] 2 [Guid] 2420593947 [EditorId] 0 [Version] 1048832 [Id] UWPPlayerX86(HoloLens-5Q6F2) [Debug] 0 [PackageName] Template3D_ph1m9x8skttmg" to [225.0.0.222:54997]...
Started listening to [0.0.0.0:55427]
PlayerConnection already initialized - listening to [0.0.0.0:55427]
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: HoloLens Graphics (ID=0x22b0)
    Vendor:   (null)
    VRAM:     604 MB
Initialize engine version: 2018.4.5f1 (7b38f8ac282e)
If your machine has multiple graphics adapters, Unity may have created a WindowContext on the wrong adapter. If you experience a black screen when playing, please restart the Editor.
 
(Filename: C:\buildslave\unity\build\Runtime/VR/VRDevice.cpp Line: 319)

Created eye textures with a "separate" layout.  The "multi-pass" stereo mode will be used.

 
(Filename: C:\buildslave\unity\build\Runtime/VR/VRDevice.cpp Line: 2280)

Windows Mixed Reality spatial locatability state changed to Active.
 
(Filename: C:\buildslave\unity\build\Runtime/VR/HoloLens/HoloLensWorldManager.cpp Line: 336)

UnloadTime: 2.459900 ms
SpectatorView is running as: User. Expected User IPAddress: 127.0.0.1
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Microsoft.MixedReality.SpectatorView.SpectatorView:Awake()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

StateSynchronizationBroadcaster: Awoken!
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Microsoft.MixedReality.SpectatorView.StateSynchronizationBroadcaster:DebugLog(String)
Microsoft.MixedReality.SpectatorView.StateSynchronizationBroadcaster:Awake()
UnityEngine.GameObject:SetActive(Boolean)
Microsoft.MixedReality.SpectatorView.SpectatorView:Awake()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

QRCodeMarkerDetectorSpatialLocalizer: Awake
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Microsoft.MixedReality.SpectatorView.SpatialLocalizer`1:DebugLog(String)
Microsoft.MixedReality.SpectatorView.QRCodeMarkerDetectorSpatialLocalizer:Awake()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

ArUcoMarkerDetectorSpatialLocalizer: Awake
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Microsoft.MixedReality.SpectatorView.SpatialLocalizer`1:DebugLog(String)
Microsoft.MixedReality.SpectatorView.ArUcoMarkerDetectorSpatialLocalizer:Awake()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Failed to call InitializeNative: System.DllNotFoundException: Unable to load DLL 'SpectatorView.OpenCV.dll': The specified module could not be found.
  at Microsoft.MixedReality.SpectatorView.SpectatorViewOpenCVInterface.Initialize (System.Single markerSize) [0x00000] in <00000000000000000000000000000000>:0 
  at Microsoft.MixedReality.SpectatorView.ArUcoMarkerDetector.Start () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.SpectatorView.SpectatorViewOpenCVInterface:Initialize(Single)
Microsoft.MixedReality.SpectatorView.ArUcoMarkerDetector:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

SpectatorView.OpenCV.dll did not initialize correctly
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
Microsoft.MixedReality.SpectatorView.SpectatorViewOpenCVInterface:Initialize(Single)
Microsoft.MixedReality.SpectatorView.ArUcoMarkerDetector:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Issue loading SpectatorView.OpenCV dll
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.SpectatorView.ArUcoMarkerDetector:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

SpatialCoordinateSystemManager: Registering spatial localizer: 0858173d-b0f4-4d19-9b33-cadc1efc96fe
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Microsoft.MixedReality.SpectatorView.SpatialCoordinateSystemManager:DebugLog(String)
Microsoft.MixedReality.SpectatorView.SpatialCoordinateSystemManager:RegisterSpatialLocalizer(ISpatialLocalizer)
Microsoft.MixedReality.SpectatorView.SpatialLocalizer`1:Start()
Microsoft.MixedReality.SpectatorView.WorldAnchorSpatialLocalizer:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Failed to call InitializeNative: System.DllNotFoundException: Unable to load DLL 'SpectatorView.OpenCV.dll': The specified module could not be found.
  at Microsoft.MixedReality.SpectatorView.SpectatorViewOpenCVInterface.Initialize (System.Single markerSize) [0x00000] in <00000000000000000000000000000000>:0 
  at Microsoft.MixedReality.SpectatorView.ArUcoMarkerDetector.Start () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.SpectatorView.SpectatorViewOpenCVInterface:Initialize(Single)
Microsoft.MixedReality.SpectatorView.ArUcoMarkerDetector:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

SpectatorView.OpenCV.dll did not initialize correctly
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
Microsoft.MixedReality.SpectatorView.SpectatorViewOpenCVInterface:Initialize(Single)
Microsoft.MixedReality.SpectatorView.ArUcoMarkerDetector:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Issue loading SpectatorView.OpenCV dll
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.SpectatorView.ArUcoMarkerDetector:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

SpatialCoordinateSystemManager: Registering spatial localizer: 2da7d277-323f-4a0d-b3bb-b2ba6d3ef70e
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Microsoft.MixedReality.SpectatorView.SpatialCoordinateSystemManager:DebugLog(String)
Microsoft.MixedReality.SpectatorView.SpatialCoordinateSystemManager:RegisterSpatialLocalizer(ISpatialLocalizer)
Microsoft.MixedReality.SpectatorView.SpatialLocalizer`1:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

SpatialCoordinateSystemManager: Registering spatial localizer: fb077e49-b855-453f-9fb5-77187b1af784
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Microsoft.MixedReality.SpectatorView.SpatialCoordinateSystemManager:DebugLog(String)
Microsoft.MixedReality.SpectatorView.SpatialCoordinateSystemManager:RegisterSpatialLocalizer(ISpatialLocalizer)
Microsoft.MixedReality.SpectatorView.SpatialLocalizer`1:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

StateSynchronizationBroadcaster: Setting up connection manager
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Microsoft.MixedReality.SpectatorView.StateSynchronizationBroadcaster:DebugLog(String)
Microsoft.MixedReality.SpectatorView.StateSynchronizationBroadcaster:SetupNetworkConnectionManager()
Microsoft.MixedReality.SpectatorView.StateSynchronizationBroadcaster:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Listening on port 7410
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Microsoft.MixedReality.SpectatorView.TCPConnectionManager:StartListening(Int32)
Microsoft.MixedReality.SpectatorView.StateSynchronizationBroadcaster:SetupNetworkConnectionManager()
Microsoft.MixedReality.SpectatorView.StateSynchronizationBroadcaster:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

SpatialCoordinateSystemManager: Registering spatial localizer: 698d46cf-2099-4e06-9ade-2fd0c18992f4
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Microsoft.MixedReality.SpectatorView.SpatialCoordinateSystemManager:DebugLog(String)
Microsoft.MixedReality.SpectatorView.SpatialCoordinateSystemManager:RegisterSpatialLocalizer(ISpatialLocalizer)
Microsoft.MixedReality.SpectatorView.SpatialLocalizer`1:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

SpatialCoordinateWorldOriginTransformer: Registering ParticipantConnected and ParticipantDisconnected events.
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Microsoft.MixedReality.SpectatorView.SpatialCoordinateTransformer:DebugLog(String)
Microsoft.MixedReality.SpectatorView.SpatialCoordinateTransformer:Start()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Setting up 1 worker threads for Enlighten.
  Thread -> id: dac -> priority: 1 
Trimming D3D resources.

**Comment by RenSiyao** [comment]
> 您使用的是HoloLens 1设备吗？如果是这样，你为x86 Release构建了SpectatorView.Native.sln吗？构建此解决方案后，有一个https://github.com/microsoft/MixedReality-SpectatorView/blob/master/tools/Scripts/CopyPluginsToUnity.bat脚本，它将这些dll添加到您的旁观者视图代码库/项目中。该错误表明dll尚未构建/放置在您的项目中。

你好，感谢你的回复，在构建SpectatorView.Native.sln是否需要安装vcpkg与Opencv，这两个的安装路径可以在其他地方吗？是否安装完这些才能够正确构建，因为我现在构建经常丢失东西或不存在。
=================================================================
![O42ZZO5R0%E_}0TMWAJVR82](https://user-images.githubusercontent.com/53859046/63841105-c224d200-c9b4-11e9-8d9e-5cbcbbdcdd9b.png)

**Comment by RenSiyao** [comment]
> 您使用的是HoloLens 1设备吗？如果是这样，你为x86 Release构建了SpectatorView.Native.sln吗？构建此解决方案后，有一个https://github.com/microsoft/MixedReality-SpectatorView/blob/master/tools/Scripts/CopyPluginsToUnity.bat脚本，它将这些dll添加到您的旁观者视图代码库/项目中。该错误表明dll尚未构建/放置在您的项目中。

我已经将 Vcpkg及OPCV安装完成
接着我生成了SpectatorView.Native.sln的 release X86 以下是我的生成结果
是否这样就是完成了呢？
1>------ 已跳过生成: 项目: SpectatorView.Compositor.SharedHeaders, 配置: Release Win32 ------
1>没有为此解决方案配置选中要生成的项目 
2>------ 已跳过生成: 项目: SpectatorView.OpenCV.CalibrationBoardGenerator, 配置: Release x64 ------
2>没有为此解决方案配置选中要生成的项目 
3>------ 已启动生成: 项目: SpectatorView.OpenCV.UWP, 配置: Release Win32 ------
4>------ 已跳过生成: 项目: SpectatorView.OpenCV.Desktop, 配置: Release x64 ------
4>没有为此解决方案配置选中要生成的项目 
5>------ 已跳过生成: 项目: SpectatorView.Compositor, 配置: Release Win32 ------
5>没有为此解决方案配置选中要生成的项目 
6>------ 已跳过生成: 项目: SpectatorView.Compositor.UnityPlugin, 配置: Release Win32 ------
6>没有为此解决方案配置选中要生成的项目 
3>cl : 命令行 warning D9030: “/Yc”与多处理不兼容；忽略 /MP 开关
3>ArUcoMarkerDetector.cpp
3>Calibration.cpp
3>SpectatorViewPlugin.cpp
3>dllmain.cpp
3>  正在创建库 D:\Unity2018.3.14\Project\Unity Project Spe\sv\src\SpectatorView.Native\Release\SpectatorView.OpenCV.UWP\SpectatorView.OpenCV.lib 和对象 D:\Unity2018.3.14\Project\Unity Project Spe\sv\src\SpectatorView.Native\Release\SpectatorView.OpenCV.UWP\SpectatorView.OpenCV.exp
3>正在生成代码
3>All 1181 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
3>已完成代码的生成
3>SpectatorView.OpenCV.UWP.vcxproj -> D:\Unity2018.3.14\Project\Unity Project Spe\sv\src\SpectatorView.Native\Release\SpectatorView.OpenCV.UWP\SpectatorView.OpenCV.dll
3>已完成生成项目“SpectatorView.OpenCV.UWP.vcxproj”的操作。
========== 生成: 成功 1 个，失败 0 个，最新 1 个，跳过 5 个 ==========

完成这步骤之后 我运行了tools/Scripts/CopyPluginsToUnity.bat但是一闪而过，其中有些警告我不知道我是否完成了正确的构建，你可以告诉我需要将构建完成的哪些文件放入Unity项目中吗？

**Comment by chrisfromwork** [comment]
It looks like your setup may not have opencv binaries resolving correctly. Did you run the vcpkg steps to build opencv prior to trying to compile SpectatorView.Native? 
https://github.com/microsoft/MixedReality-SpectatorView/blob/master/src/SpectatorView.Native/README.md

在管理员模式下打开命令提示符
导航到要在其中存储存储库的文件夹（例如：c：\ git）
git clone https://github.com/Microsoft/vcpkg
cd vcpkg
.\bootstrap-vcpkg.bat
.\vcpkg integrate install

.\vcpkg install protobuf:x86-windows
.\vcpkg install opencv[contrib]:x86-uwp --recurse
.\vcpkg install opencv[contrib]:x64-windows --recurse

**Comment by chrisfromwork** [comment]
I'm going to close this issue for now. Please reopen this issue if you are still experiencing problems.
