### ISSUE TITLE
SpectatorView项目拉取

### ISSUE THREAD

**Issue by RenSiyao** [microsoft/MixedReality-SpectatorView#200]
![VDZ%5G1 Q~` V5X{{I_4 EM](https://user-images.githubusercontent.com/53859046/63634483-a7d3b700-c689-11e9-88fd-f3effc528a8a.png)

Could you please tell me the detailed operation of this step? Because I didn't pull the file successfully, I think it may be related to this step.

**Comment by RenSiyao** [comment]
> 请通过导航到URL来查看这些存储库的许可证，然后在您的计算机上本地运行该脚本。
> 
> 另外，你看到了什么样的问题？

我并没有看到什么许可证，他们都是一些空文件夹

**Comment by andreiborodin** [comment]
Closing the issue as resolved, please re-open if you encounter any new issues.
