### ISSUE TITLE
Hololens与Android连接问题

### ISSUE THREAD

**Issue by RenSiyao** [microsoft/MixedReality-SpectatorView#208]
当我将所需文件配置完成后，Hololens与android可以正常连接。但是Android看不到Hololens里的内容。 但是Hololens与Android似乎可以彼此看到坐标。【我使用的是Hololens1，但是android似乎展示的标记为ARUco，但是还是可以正常连接，我的项目是否正确？】

**Comment by chrisfromwork** [comment]
Original question:
"When I configured the required files, Hololens and android can connect normally. But Android can't see the contents of Hololens. But Hololens and Android seem to be able to see the coordinates of each other. [I am using Hololens1, but android seems to display the mark as ARUco, but still can connect normally, is my project correct?"

Answer:
If the Android device shows and hides the ArUco marker, the marker has been detected by the HoloLens and a network connection has been established. Even if this spatial alignment process fails, you should be able to see content from the HoloLens on the android device (it may be in the wrong location). This problem sounds like you may not have updated your asset caches correctly. Did you run Spectator View -> Update All Asset Caches from the Unity toolbar? This step should be conducted one time, and the created asset caches should be shared across builds. Recreating this asset caches for different platforms will break the synchronization logic. See Before Building here https://microsoft.github.io/MixedReality-SpectatorView/doc/SpectatorView.Setup.html

如果Android设备显示并隐藏了ArUco标记，则HoloLens已检测到标记，并且已建立网络连接。 即使此空间对齐过程失败，您也应该能够在Android设备上看到来自HoloLens的内容（它可能位于错误的位置）。 这个问题听起来可能没有正确更新您的资产缓存。 您是否从Unity工具栏运行Spectator View  - > Update All Asset Caches？ 此步骤应该执行一次，并且创建的资产缓存应该跨构建共享。 为不同平台重新创建此资产缓存将破坏同步逻辑。 请参阅之前构建此处https://microsoft.github.io/MixedReality-SpectatorView/doc/SpectatorView.Setup.html

**Comment by RenSiyao** [comment]
> 原始问题：
> “当我配置所需的文件时，Hololens和android可以正常连接。但Android无法看到Hololens的内容。但是Hololens和Android似乎能够看到彼此的坐标。[我正在使用Hololens1但是android似乎将标记显示为ARUco，但仍然可以正常连接，我的项目是否正确？“
> 
> 答：
> 如果Android设备显示并隐藏了ArUco标记，则HoloLens已检测到标记，并且已建立网络连接。即使此空间对齐过程失败，您也应该能够在Android设备上看到来自HoloLens的内容（它可能位于错误的位置）。这个问题听起来可能没有正确更新您的资产缓存。您是否从Unity工具栏运行Spectator View - > Update All Asset Caches？此步骤应该执行一次，并且创建的资产缓存应该跨构建共享。为不同平台重新创建此资产缓存将破坏同步逻辑。请参阅之前构建此处https://microsoft.github.io/MixedReality-SpectatorView/doc/SpectatorView.Setup.html
> 
> 如果Android设备显示并隐藏了ArUco标记，则HoloLens已检测到标记，并且已建立网络连接。即使此空间对齐过程失败，您也应该能够在Android设备上看到来自HoloLens的内容（它可能位于错误的位置）。这个问题听起来可能没有正确更新您的资产缓存。您是否从Unity工具栏运行观察者视图 - >更新所有资产缓存？此步骤应该执行一次，并且创建的资产缓存应该跨构建共享。为不同平台重新创建此资产缓存将破坏同步逻辑。请参阅之前构建此处https://microsoft.github.io/MixedReality-SpectatorView/doc/SpectatorView.Setup.html


感谢您的回复。我将会尝试一下你的方法。

**Comment by chrisfromwork** [comment]
I'm going to close this issue for now. Please reopen the issue if you encounter additional problems.

我现在要结束这个问题。如果遇到其他问题，请重新打开此问题。
