### ISSUE TITLE
Adding Reference to your project in Mac

### ISSUE THREAD

**Issue by bharath09vadde** [microsoft/MixedReality-SpectatorView#211]
rm-mac02:GC_Assist_SV mac-02$ sv/tools/Scripts/AddDependencies.bat "Assets" "sv"
sv/tools/Scripts/AddDependencies.bat: line 1: @ECHO: command not found
sv/tools/Scripts/AddDependencies.bat: line 3: SET: command not found
sv/tools/Scripts/AddDependencies.bat: line 4: SET: command not found
sv/tools/Scripts/AddDependencies.bat: line 5: PowerShell.exe: command not found

I have been receiving this for the past three days and I couldn't proceed from here because of this issue. can you guys help me solve the issue.

**Comment by andreiborodin** [comment]
Are you trying to setup a new project? We didn't create an equivalent bash script to the AddDependencies.bat, and .bat won't work on Mac. How familiar are you with setting up symbolic links on a Mac?

**Comment by bharath09vadde** [comment]
I am not much familiar with MacBook and also the Terminal app. But I will look into the topic of setting up symbolic links on a mac and get the info about adding references to the project. Can you please tell me if anything that has to be changed on the mac if I am following the procedure given in the Git Hub.
Thanks for the reply.

**Comment by andreiborodin** [comment]
Essentially we have the Powershell script AddDependencies.ps1, that's what AddDependencies.bat calls; perhaps you could try installing Powershell for Mac:
https://github.com/microsoft/MixedReality-SpectatorView/blob/d2876f64994bfe669f877d15939cba88e99883c8/tools/Scripts/AddDependencies.ps1#L57

I haven't tried this scenario, so this is unchartered waters; I'll see if I can find some time to try this.

**Comment by bharath09vadde** [comment]
Hey thanks for the wonderful info, I tried to install powershell and got it working. I have also installed Homebrew for the final step to work before deploying it to my iOS device. But the problem is I have deployed my Hololens application with all the steps specified and also built and deployed the sample iOS SpectatorView scene and I have entered the IP address of my Hololens but still it does not show any thing that was shown in Hololens. Is it necessary that all the game objects present in my Hololens scene should be present in my iOS scene? Is there something I am missing?(P.S : I have also deployed the sample Hololens scene and tried too but I couldn't get working).

**Comment by andreiborodin** [comment]
That's great! 

Ok, so what localization method are you using?

Also, when you say "Sample HoloLens scene" you mean the one that contains the demo content?

Basically our SpectatorView scenes are almost empty, they connect to the host device built out of the same project, and begin synchronizing data. The host encodes all assets to Guids using AssetCaches (that need to be regenerate for new projects, or new/removed assets), and transmits those Guids. The SpectatorView scene will use the same AssetCaches (since same project) to load up the necessary assets.

**Comment by bharath09vadde** [comment]
I have done the symbolic linking of the folders manually in the mac. I am using Azure spatial anchors method for localization. I have given the Azure account ID and the primary key in the edit settings. Can you please tell me the objects that has to be added in the scene to get the spectator view working. Since I am using my iPhone as the spectator, I have used MacBook to build the iOS application and Windows to deploy the app to Hololens. Is there something you think that I am missing? I have directly deployed the SpectatorView.iOS scene as mentioned in the procedure, but for the Hololens I tried to deploy the scene that I am working on as well as the SpectatoirView.Hololens scene. None of them worked. Thanks for the amazing assistance :)

**Comment by andreiborodin** [comment]
Ok, let me check a few concrete steps to ensure I understand your state.

Did you do Step 7 of this: https://github.com/microsoft/MixedReality-SpectatorView#basic-unity-setup

And did you follow these steps for Azure Spatial Anchors setup: https://github.com/microsoft/MixedReality-SpectatorView/blob/master/doc/SpectatorView.Setup.md#azure-spatial-anchors

Specifically, did you update CocoaPods:
https://github.com/microsoft/MixedReality-SpectatorView/blob/master/doc/SpectatorView.Setup.md#azure-spatial-anchors-on-ios

**Comment by bharath09vadde** [comment]
Yes, I have updated all the Asset caches, done the Azure Spatial Anchors setting up procedure without missing anything. I have installed the Cocoapads and compiled my application using the Xcode workspace(not the Xcode project).

**Comment by andreiborodin** [comment]
Ok great, thanks for confirming. I presume the WiFi you connect to has internet access, so maybe we are just failing to localize on the spectator device. Try the following:
- Launch the HoloLens experience
- Walk around the space for about 30 seconds, looking around (smooth movement)
- Launch the iOS and connect to the HoloLens
- Look for the Anchor visual: the XYZ Axis visual on the HoloLens (this means the Anchor was succesfully created upon joining)
- Look for the Anchor visual on the iOS (this means the Anchor was localized at that position)

Let me know what else is observed.

**Comment by bharath09vadde** [comment]
I don't see any anchor visual. Is it because of the problem in setting up the Azure account or the Spatial Anchors account? I don't see any anchors details in my Spatial Anchors account. Here I attached some screenshots from my project which would be easy for you to understand the state of the project.
![Hololens Scene view](https://user-images.githubusercontent.com/33687324/64420511-bbc2e400-d09f-11e9-856b-db30d5c52ac0.PNG)
![SpectatorView_Settings](https://user-images.githubusercontent.com/33687324/64420512-bbc2e400-d09f-11e9-93ea-9a35bcec7ac1.PNG)
![iOS Scene View](https://user-images.githubusercontent.com/33687324/64420513-bc5b7a80-d09f-11e9-8424-42b853ea3691.png)
![iOS build folder](https://user-images.githubusercontent.com/33687324/64420514-bc5b7a80-d09f-11e9-92e0-38b80d09a59f.png)
![iOS SpectatorView Settings](https://user-images.githubusercontent.com/33687324/64420516-bc5b7a80-d09f-11e9-8ee9-c19af710c346.png)
![AzureSpatialAnchors_Account](https://user-images.githubusercontent.com/33687324/64420517-bc5b7a80-d09f-11e9-9677-46457bdc29f1.PNG)

**Comment by andreiborodin** [comment]
Ok, so yeah, for some reason we aren't creating the Azure Spatial Anchor, could we do the following:
- Build your UWP to a fresh new project
- Run through the experience, and *close the app*.
- Download the Unity Log file:
-- Enable [Web Management](https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-windows-device-portal#setting-up-hololens-to-use-windows-device-portal) portal (visuals are a bit dated, but very similar instructions)
-- Go to File Explorer menu on the left, and navigate to LocalAppData\Packages<productname>\TempState\UnityPlayer.log
-- Attach the log file to this thread.

**Comment by bharath09vadde** [comment]
[UnityPlayer.log](https://github.com/microsoft/MixedReality-SpectatorView/files/3589374/UnityPlayer.log)

**Comment by andreiborodin** [comment]
I downloaded the file and removed it from thread here, just in case. Investigating.

**Comment by andreiborodin** [comment]
Ok, a couple of things I see:
- Looks like the device lost tracking while it was trying to create an anchor: 
-- See this "Windows Mixed Reality spatial locatability state changed to Inhibited."
-- Then several lines below: "Failed to create a HoloLens SpatialAnchor. Device may have lost tracking."
- Also separately it looks like the Asset Caches were not regenerated:
-- Error Message: "Could not find the Mesh asset for GameObject Quad. Check the NetworkAssetCache ..."

I suppose that this time it failed to create an anchor due to tracking issue, but I also presume it may have succeeded in the past, and the second error would explain why no visuals were encountered. Try regenerating asset caches (Step 7 of [Basic Unity Setup](https://github.com/microsoft/MixedReality-SpectatorView#basic-unity-setup))

**Comment by bharath09vadde** [comment]
Hello,
The Gameobject Quad is from another scene in the project which is not added in the build. I will try to do the process once again, this time with a simple scene. If possible, Can you create a sample project?
Thanks

**Comment by andreiborodin** [comment]
We have two sample projects checked into the repo, if you want to try those out:
- [Build 2019 Demo](https://github.com/microsoft/MixedReality-SpectatorView/tree/master/samples/Build2019Demo.Unity)
- [General Sample] (https://github.com/microsoft/MixedReality-SpectatorView/tree/master/samples/SpectatorView.Example.Unity)

Keep in mind, I referenced the master branch above, I presume you are on a release branch. Path should be same.

**Comment by andreiborodin** [comment]
Closing, and if additional issues occur please re-open or create a new issue.
