### ISSUE TITLE
Compilation fails:Command failed error 1

### ISSUE THREAD

**Issue by stonerey** [microsoft/MixedReality-SpectatorView#220]
![error](https://user-images.githubusercontent.com/22309438/65063206-5bda1080-d9b0-11e9-85f8-09c477fc5f13.PNG)

**Comment by stonerey** [comment]
Unity Version :2018.3.14f1。This is the same error when I use the unity version 2018.4.8f1

**Comment by chrisfromwork** [comment]
@stonerey do you know what commit/branch you are using for MixedReality-SpectatorView?

**Comment by stonerey** [comment]
release/1.0.0

**Comment by chrisfromwork** [comment]
I don't know that we have heavily tested building an appx through the Unity editor. Are you attempting to build this solution with MRTK build tools?

You may be able to unblock yourself by running the default unity build for UWP and then building your solution in visual studio to deploy to your device.

On an unrelated note, we found some issues in release/1.0.0. I would suggest moving to release/1.0.2 for better spatial alignment quality.

**Comment by chrisfromwork** [comment]
If this is indeed an issue when using the MRTK appx generation tools, we can look into this on our end.

**Comment by stonerey** [comment]
I build this solution with MRTK build tools.Thank you for your reply.

**Comment by chrisfromwork** [comment]
Update:

I was able to repro this locally. This looks to be a failure based on some NuGet package dependencies that don't get restored from the Unity editor. I am going to track down some MRTK owners to figure out if they have a suggested fix. They are reassessing their build tools for their 2.2.0 release.

In terms of an immediate workaround, i have verified the following works locally:
1) Build the project using the default unity Build Settings window (Build Settings -> Include Finished_Scene for HoloLens -> Build)
2) Open the generated application solution in visual studio to then build and deploy.

I realize that this is a less than ideal solution for building. I believe that someone will have to fix the nuget restore problem in the MRTK tools but do not know when this fix will become available. Once it is ready for consumption, we will update our samples.

**Comment by chrisfromwork** [comment]
Added a call out to this issue in the MRTK planning issue here: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5950

**Comment by chrisfromwork** [comment]
Closing this issue for now based on a lack of activity. We will plan on tracking fixes to this build tool with microsoft/MixedRealityToolkit-Unity#5950

Please reopen this issue as needed.
