### ISSUE TITLE
Extreme FPS drop when Spectator connects on HoloLens 2

### ISSUE THREAD

**Issue by ALaurain** [microsoft/MixedReality-SpectatorView#230]
Hello, I am developing an application for the HoloLens2 using the new Spectator View submodule. I have tried building to iOS and Android, and have tested both the QR Code and Azure Spatial Anchors features. In all these scenarios I am able to view my holograms on the spectating device. However, no matter what changes I make, the FPS always drops to around 10 on the HoloLens when a spectator connects. When I kill the spectating app, the FPS jumps back to normal (around 40-45). Are there any ideas around what could be happening in my application? Is this a known issue that has happened to others? Any help would be greatly appreciated

To elaborate: I have the "automatically Broadcast All Gameobjects" checkbox set to false, and I have the GameObjectHierarchyBroadcaster script assigned to my "WorldRoot" gameobject. This object is the parent to all the holograms I want networked across to the spectator
I also noticed that many of my shaders (Microsoft standard shaders) are not rendering correctly on the spectating device. I did a full scene build onto ios and Android and found that the shaders are supported when the scene is built to the device directly, but when they are networked across, they break entirely

**Comment by arsi0001** [comment]
Had also an project, where I should use the inspector. Same story → if broadcasting all game objects I got 1 fps, if broadcasting only certain objects I got 10 fps. Would also be interested in a solution/fix

**Comment by chrisfromwork** [comment]
We are in the process of assessing tooling for better tuning these synchronization experiences. I am going to tag this issue as next release to prioritize improving things.

Currently, there are a few items floating around that may or may not prove useful:
1) In addition to placing GameObjectHierarchyBroadcasters in your scene, you can also tag items to not be synchronized with "SpectatorViewHidden" and "SpectatorViewChildrenHidden" tags. https://github.com/microsoft/MixedReality-SpectatorView/blob/f9ff8f43f45d88b25b94854288f59797aae93ea8/src/SpectatorView.Unity/Assets/SpectatorView/Scripts/StateSynchronization/TransformBroadcaster.cs#L15

2) We have some old performance monitoring logic that may be tapped into via the video camera filming experience to see in the Unity editor the performance of the HoloLens experience. We will likely expand on this to try and improve the overall understanding of what game objects/components are causing the largest bottlenecks:
https://github.com/microsoft/MixedReality-SpectatorView/blob/cd7b0a08ea500daf15667cf677ba42338c13f4c7/src/SpectatorView.Unity/Assets/SpectatorView/Scripts/StateSynchronization/StateSynchronizationPerformanceMonitor.cs

I do not know that either of these things suggestions will fulfill your twos needs. If there are specific feature asks or functionality that you would like to see, do let us know.

In regards to the shader issue, we have seen things like this before:
https://github.com/microsoft/MixedReality-SpectatorView/issues/176
I will go ahead and increase the priority of this issue based on this additional feedback.

**Comment by chrisfromwork** [comment]
Another item you an look at, if you go choose 'Spectator View -> Edit Global Performance Parameters' in the toolbar, you will generate a prefab that contains performance parameters. Here you can change the frequency that different synchronized parameters are assessed. I think by default, all parameters are assessed continuously throughout the application life cycle. You may be able to opt to have some these parameters only checked at start to improve performance. https://github.com/microsoft/MixedReality-SpectatorView/blob/e5289394691802a331875d61beec68ac10d6169c/src/SpectatorView.Unity/Assets/SpectatorView/Scripts/StateSynchronization/DefaultStateSynchronizationPerformanceParameters.cs#L12

**Comment by chrisfromwork** [comment]
We've added documentation and richer performance monitoring so that folks can understand what the bulk of their perf drops are related to. There are some different steps now called out that can help with reducing the synchronization time on the HoloLens device. Please try some of these different approaches and reopen this issue as needed. I believe this may be the main amount of perf work that we address for the next release. We can schedule more perf improvements in subsequent releases.
