### ISSUE TITLE
Documentation does not state how to create and send an Azure Spatial Anchor for alignment

### ISSUE THREAD

**Issue by ALaurain** [microsoft/MixedReality-SpectatorView#237]
Hello,
I am developing an application for the HoloLens 2 and ran into some issues trying to setup Azure Spatial Anchors for spectator view. I setup and have spectator view working currently using your prefab provided in this Toolkit. I use Azure to connect the devices and share information between my HL and an iOS spectator. I can run the entire application and the spectating device can observe the hologram interactions just fine. However, I realized that no where in the documentation provided here does it state that you need to, or how to create an Azure Spatial Anchor and share that coordinate across to the spectating device. This was an issue discovered in some QA sessions. So currently all my spectating holograms reference the world origin of where the spectating device application is launched, instead of syncing with the HoloLens and aligning their spatial environments.

So my question is, how do I create an Azure spatial anchor and sync that across to my spectating devices to align their worlds? I have been digging through the Toolkit code and have a decent understanding of what's going on behind the scenes. But nowhere in the code or documentation does it state how or where to create a spatial anchor and share it. The documentation really needs to be more explicit in this area. As a developer I did not know this was a task I needed to perform, as I assumed this was already being done "behind the scenes" in the toolkit. Any help in  this area would be wonderful. Thanks

**Comment by andreiborodin** [comment]
Hey ALaurain, thanks for the note! 

I would like to elaborate on the observation, are you not seeing the anchor created with the service, or are you just observing the holograms not lining up?

The Azure Spatial Anchor is created by the host device when the spectator connects, and you don't need to do anything explicitly. However, if you are observing that the anchor is not being retrieve on iOS, could you tell me if you did these steps for iOS:
https://github.com/microsoft/MixedReality-SpectatorView/blob/master/doc/SpectatorView.Setup.md#azure-spatial-anchors-on-ios

**Comment by ALaurain** [comment]
Hello and thanks for the reply @andreiborodin,
I replicated all those iOS steps during my development phase and was able to get the app to run without error, and connect to the hosting HoloLens. However, I noticed that the worlds did not align unless both apps were launched form the exact same spot within the room (so the camera origin was the same). So it seems as if the spectating app is not referencing the shared anchor to align the worlds. What should I see created on the spectator side when the app connects to the HL? I can run a test in Unity to make sure this object is being created. Do I need to do anything with this created object to align the cameras/world? Thanks

**Comment by andreiborodin** [comment]
Well, let's do the very first thing, let's confirm whether we are creating the anchor to the service. If you login to your Azure portal account, and go to Azure Spatial Anchors, under overview see if the graphs show that anchors are created?

If it is, the next steps I would do:
1. Turn on the HoloLens and launch into the experience
2. Work around your space for about 30 seconds slowly panning in various directions.
3. Connect your phone device, ensure facing different direction and location from Hololens starting position.
4. Move the device around the space slowly, looking around at the same environment. It should pop into place within 5 seconds, but let's do it for about 30 seconds to be sure.

If the anchors aren't created, that means a possible bug or misconfiguration with creation; if they are but space doesn't align then possible bug with retrieval.

**Comment by ALaurain** [comment]
In the attached image you will see that the spatial anchors are being created. 
![SpatialAnchor](https://user-images.githubusercontent.com/7387611/66514604-7c772100-eaab-11e9-9cd8-c87f615c75cb.png)

Scanning the environment thoroughly for 30 seconds does not seem to help my situation at all. I was already previously doing this (though not to the "30 second" extent that you described), to no avail

**Comment by andreiborodin** [comment]
Ok, so the anchors are successfully created, but it appears not in the past 4 days? The scanning for 30 seconds should happen before the application on iOS connects to the host.

Could you run your application with the XCode debugger attached? You would need to also set "Debug Build" in Build Settings in Unity when you build your debugger.

I would like to get the log of what's going on in the iOS build, also, is it possible for us to jump onto Slack to chat through the issues?

**Comment by jessedsiegel** [comment]
This sounds like the problems I've had, except I'm trying to align objects between HoloLens and Android, or two HoloLens devices. Spending more time mapping the area on HoloLens before connecting on Android seems to have helped, but I'm still getting the same results on my spectating HoloLens, where objects are just placed relative to its starting position.

**Comment by andreiborodin** [comment]
@jessedsiegel, we haven't experimented with supporting HoloLens as a spectator and there is no out-of-the-box scene that would be configured for that; so explains why HL to HL didn't localize for you.

You could experiment yourself, if you do take a look at the SpectatorView.HoloLens scene, it's configured as a host (user), to modify you would need to do the following:
- On the root **SpectatorView** game object, under **Spectator View** behaviour change **Role** to **Spectator**
- On the **SpectatorView -> SpatialCoordinateSystem -> CameraTransform** game object, under **Spatial Coordinate Transformer** behaviour, set **Shared Coordinate Origin** to the **Parent of Main Camera** in the scene.

Let me know what are your results after doing this.

**Comment by jessedsiegel** [comment]
Seems like that did the trick. Thanks!

**Comment by andreiborodin** [comment]
Cool! Would you be up for submitting a PR to duplicate that scene into: SpetatorView.HoloLens.Spectator, with those changes applied?

**Comment by andreiborodin** [comment]
@ALaurain, the thread got a bit hijacked, however, any luck with your issue? Slack would be a great channel to get on a live chat to solve it.

**Comment by ALaurain** [comment]
Hey @andreiborodin it seems as though I need to be invited to the workspace https://holodevelopers.slack.com/messages/C69D5S5K9 before I can join. I would be happy to provide you with my Slack info. From there I could provide you with some more info into the other major blocker preventing me from running these simple tests

**Comment by andreiborodin** [comment]
Ah yes, please submit the form here: aka.ms/holodevelopers

**Comment by andreiborodin** [comment]
Closing this issue, the resolution for @ALaurain  was to setup the camera shared origin as part their custom spectator scene:
On the SpectatorView -> SpatialCoordinateSystem -> CameraTransform game object, under Spatial Coordinate Transformer behaviour, set Shared Coordinate Origin to the Parent of Main Camera in the scene.

I submitted a PR with some documentation improvement, also with the HoloLens spectator scene in regards to @jessedsiegel comment.
