### ISSUE TITLE
SetupRepository.bat will not run due to Execution Policy

### ISSUE THREAD

**Issue by alltheRealities** [microsoft/MixedReality-SpectatorView#239]
I am stuck trying to run the SetupRepository.bat file in CMD. Powershell also fails. Error is as follows:

& : File C:\Users\"username"\repos\HololensSpectatorView\Hololens\sv\tools\Scripts\SetupRepository.ps1 cannot be
loaded. The file C:\Users\"username"\repos\HololensSpectatorView\Hololens\sv\tools\Scripts\SetupRepository.ps1 is
not digitally signed. You cannot run this script on the current system. For more information about running scripts and
setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
+ & 'C:\Users\"username"\repos\HololensSpectatorView\Hololens\sv\to ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by chrisfromwork** [comment]
What branch/commit are you using?

SetupRepository.bat in release/1.0.3 attempts to provide an '-ExecutionPolicy Bypass' flag that typically prevents this error from occurring. Are you running CMD as an administrator?

One workaround is to allow non-digitally signed scripts to run. This may leave your machine vulnerable but would get past the error you are seeing. You could run this from a powershell window before running SetupRepository.ps1:

`Set-ExecutionPolicy -ExecutionPolicy Bypass`

[Microsoft Documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-6)
[Blog Overview](https://www.msnoob.com/powershell-script-is-not-digitaly-signed.html)

**Comment by alltheRealities** [comment]
Yes, it is an admin CMD. I tried bypassing and get this error:

Set-ExecutionPolicy : Windows PowerShell updated your execution policy successfully, but the setting is overridden by a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective execution policy of AllSigned. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more information please see "Get-Help Set-ExecutionPolicy".
At line:1 char:1
+ Set-ExecutionPolicy -ExecutionPolicy Bypass
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Set-ExecutionPolicy], SecurityException
    + FullyQualifiedErrorId : ExecutionPolicyOverride,Microsoft.PowerShell.Commands.SetExecutionPolicyCommand

**Comment by chrisfromwork** [comment]
What did you see when running `Get-ExecutionPolicy -List`?

**Comment by alltheRealities** [comment]
Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       AllSigned
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser    Unrestricted
 LocalMachine          Bypass

**Comment by chrisfromwork** [comment]
It looks like you successfully set your LocalMachine and CurrentUser policies, but it may be overridden by the MachinePolicy. There are what look like some hacky workarounds on the internet for setting your machine policy:
https://absolute-sharepoint.com/2014/03/change-powershell-machinepolicy-execution-policy-windows-server-2012r2.html

If you don't have admin permissions/the ability to set a MachinePolicy ExecutionPolicy, you may need to look into signing the powershell script: https://sid-500.com/2017/10/26/how-to-digitally-sign-powershell-scripts/

At this time, I don't believe we will check in signed scripts to the repo.

**Comment by alltheRealities** [comment]
Ok. That combined with [this ](https://www.youtube.com/watch?v=lB-tdUgptVg)fixed the issue. Thanks!

**Comment by chrisfromwork** [comment]
Happy to hear things are working! :)

We're going to close this issue for now. Feel free to reopen/open additional issues if you encounter more problems in the future.

One final thought, you may already know this, but there is a mixed reality developer channel on slack with a specific spectator view conversation. The folks on there are fairly responsive and the chat based communication may help for more quickly working through some of these problems. If you're interested in joining the holodevelopers slack community, you can sign up [here](http://www.aka.ms/holodevelopers).
