### ISSUE TITLE
Cannot Run AddDependencies.bat

### ISSUE THREAD

**Issue by alltheRealities** [microsoft/MixedReality-SpectatorView#254]
It says "Invalid Unity project path." I tried to follow the procedure exactly in terms of where to store the repo and the Unity project but perhaps I did something wrong? CMD output below:

C:\Users\myusername\repos\HololensRepo>sv\tools\Scripts\AddDependencies.bat -AssetPath "Assets" -SVPath "sv"
C:\Users\myusername\repos\HololensRepo\sv\tools\Scripts\AddDependencies.ps1 : Invalid Unity project path
specified: C:/Users/myusername/repos/HololensRepo/-AssetPath
At line:1 char:1
+ & 'C:\Users\myusername\repos\HololensRepo\sv\tools\Scripts\AddDep ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,AddDependencies.ps1

Note, this path should be equal to the submodule location relative to your project's repository root.

Example Usage: AddDependencies.bat Assets sv

Press any key to continue...

C:\Users\myusername\repos\HololensRepo>

**Comment by chrisfromwork** [comment]
This may be some bad documentation depending on what branch you are using. I added the -AssetPath and -SVPath argument flags recently (maybe in release/1.0.3). It looks like the -AssetPath flag is getting used as the Unity project assets folder, which suggests that you may need to try running:

C:\Users\myusername\repos\HololensRepo>sv\tools\Scripts\AddDependencies.bat "Assets" "sv"

FWIW, I would suggest moving to release/1.0.3 in your spectator view submodule. Running AddDependencies.bat for an older release will cause some android/ASA assets to get placed in the wrong location.

**Comment by alltheRealities** [comment]
Sorry, the release of what? This repo? Would I need to re-clone the repo? I cloned it the same day I reported the issue so it should be the latest. Here is the latest result:


C:\Users\myusername\repos\HololensRepo>sv\tools\Scripts\AddDependencies.bat "Assets" "sv"

C:\Users\myusername\repos\HololensRepo\sv\tools\Scripts\AddDependencies.ps1 : Invalid Unity project path
specified: C:/Users/myusername/repos/HololensRepo/Assets
At line:1 char:1
+ & 'C:\Users\myusername\repos\HololensRepo\sv\tools\Scripts\AddDep ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,AddDependencies.ps1

Note, this path should be equal to the submodule location relative to your project's repository root.


Example Usage: AddDependencies.bat Assets sv

Thank you.

**Comment by chrisfromwork** [comment]
So your sv folder contains a submodule reference to microsoft/MixedReality-SpectatorView. You can cd into this folder and change the branch it references in a similar manner to how you would change branches in a standard git repo. This will allow you to move to the submodule referenced in the sv folder to the release/1.0.3 branch:

cd sv
git fetch origin release/1.0.3
git checkout release/1.0.3

What content is in the C:\Users\myusername\repos\HololensRepo directory? Does it contain a Unity project? Calling AddDependencies.bat requires specifying your Unity project's assets folder from the repo root. You might need to call something like the following based on your project setup:

C:\Users\myusername\repos\HololensRepo>sv\tools\Scripts\AddDependencies.bat "Your\Unity\Project\Assets" "sv"

Right now it looks like you are specifying that C:\users\myusername\repos\HololensRepo\Assets is your project's asset path. Does this folder exist in your local setup?

**Comment by alltheRealities** [comment]
Ahhhhh, ok. User-error. I thought that was it but I didn't quite specify the right path when I was trying different things. Thanks.

**Comment by chrisfromwork** [comment]
No stress. We are happy to help.

I'm going to close this issue for now. Please reopen as needed.
