### ISSUE TITLE
GoogleAR Unity errors after adding dependencies

### ISSUE THREAD

**Issue by jmc-crash** [microsoft/MixedReality-SpectatorView#258]
I have successfully added dependencies to my own project using AddDependencies.bat. Successful in that all symlinks have resolved correctly and are pointing to the right places. 

When I open the Unity project (Unity 2019.1.12f1), I am getting multiple namespace issues (see image attached) only for GoogleARCore. Do I need to add any further packages etc to the project?

![GoogleARCoreUnityErrors](https://user-images.githubusercontent.com/54383366/67526437-3fe52f80-f711-11e9-88c7-4bd1939cc262.png)

Edit: It appears the Unity libraries have changed in terms of at least Networking which is causing some of those issues. Is this version of Unity too recent?

**Comment by chrisfromwork** [comment]
We're planning to support AR Foundation over time. Right now we officially support Unity 2018.3.14. I have also personally had success with some versions of Unity 2018.4.*

If you can go back to an older version of Unity, you may be able to immediately unblock yourself. The version of ARCore we were using was influenced by what azure spatial anchors supported.

FWIW, you could also remove this ARCore dependency and set up your own AR Foundation based scene if you are using marker detection for spatial alignment. We only use ARCore for its android camera prefab in the current release branches (Its also used for tracking information in our current master branch). So theoretically, if you removed the arcore camera in the SpectatorView.Android scene and traded it out with an AR Foundation camera, you may be able to get passed these errors.

**Comment by chrisfromwork** [comment]
I'll sync with the team today. We need to move to a newer version of ASA, which might result in moving to a newer version of ARCore. I'm not sure if there will be a path for this project to support Unity 2019 without moving to Unity's AR Foundation.

**Comment by jmc-crash** [comment]
Okay, thanks for that, all makes sense! I'll just push the project back to an earlier version until the next release.

**Comment by chrisfromwork** [comment]
I'm going to close this issue for now and track moving to Unity 2019 here #296
