### ISSUE TITLE
ARUCO Hololens gen 1

### ISSUE THREAD

**Issue by AtixD** [microsoft/MixedReality-SpectatorView#259]
Hey. The spectator on the Hololense gen 1 stopped working. Synchronization with iOS and the marker stopped showing up literally today, after updating the dependencies. What can it be connected with? Branch release/1.0.3.

**Comment by chrisfromwork** [comment]
https://github.com/microsoft/MixedReality-SpectatorView/pull/228/files
https://github.com/microsoft/MixedReality-SpectatorView/pull/222/files
https://github.com/microsoft/MixedReality-SpectatorView/pull/207/files

The three patches in release/1.0.3 didn't directly effect the ArUco native plugin or c# wrapper scripts. But, if you switched branches in a submodule, maybe you ended up removing the compiled dlls?

In hopes of better troubleshooting, i'd start with the following checklist of questions:
1) Are you seeing any errors in the visual studio debug console when running your spectator view experience on the HoloLens?
2) Does the iOS device display the ArUco marker or scene content from the HoloLens device? If no scene content is shown it may be that the network connection is no longer working. If scene content is shown, but the marker isn't shown, it may be that the supported localizers are now misconfigured.
3) Does the iOS device show the ArUco marker but the HoloLens fails to detect said marker? If so, it may be that the HoloLens is failing to use the ArUco marker detector. This could happen if the camera permission is no longer configured correctly. It could also be that the opencv dlls aren't working correctly or are missing. I believe if the opencv dlls are missing, you will see some sort of error in the logs at least during initialization.

**Comment by AtixD** [comment]
Hi, the problem was in the assembly itself through visual studio, for some reason the dll for aruco itself was taken from a nonexistent path.

**Comment by chrisfromwork** [comment]
Were you able to resolve your issue?

**Comment by AtixD** [comment]
Yes, thanks.
