### ISSUE TITLE
Add support of Azure Kinect 

### ISSUE THREAD

**Issue by tomkrikorian** [microsoft/MixedReality-SpectatorView#262]
It's hard to convince clients to dedicate one hololens device for the spectator view. 
Could it be possible in the future to use a azure kinect device to replace a hololens 2 device + Camera ?

**Comment by chrisfromwork** [comment]
Our lower cost solution is typically using a mobile device. Azure kinect doesn't have obvious support for camera tracking. Are there specific asks that rule out using a mobile device?

**Comment by tomkrikorian** [comment]
For a static spectator view on a TV Screen for an exhibition, that's our use case.

**Comment by chrisfromwork** [comment]
Is there a specific reason you want to use a Kinect for this? Theoretically, you could do this with any sort of usb/webcam/capture card camera if you knew the camera intrinsics and could locate a marker in the scene once the camera was placed in its static location. Azure Kinect does report this camera intrinsic information, but other webcams might, too. It could also be calculated with the opencv logic that we use to calculate camera intrinsics for our DSLR camera rig.

Have you tried using a mobile device for this TV Screen setup? USB-C to hdmi adapters do exist for some phones/we have used these in the past for some of our demos. We can look into enabling static camera setups with the editor/a PC, but our working group would be more likely to flag this issue as a high priority if you were experiencing some sort of fundamental blocker with the mobile setup?

**Comment by tomkrikorian** [comment]
We want to use kinect to also handle occluding people getting in front of the augmented reality scene. 

Mobile devices are out of the equation since it is for an exhibition that will run for months in a specific area of 6x6m and we need the spectator view to be easy to setup and static. 
We also can't use azure anchors because we won't get internet access on the site so we thought our best bet was to use azure kinect for all these reasons.

**Comment by chrisfromwork** [comment]
Thanks for this perspective, I will work to get this feedback into our next planning cycle.

**Comment by chrisfromwork** [comment]
@matthejo and @RachelRattay were able to get a stationary azure kinect experience working that uses depth/body tracking for better compositing.

Let us know if you hit any issues when trying things out. :)
