### ISSUE TITLE
Record audio from headset camera audio listener

### ISSUE THREAD

**Issue by jhurlbut** [microsoft/MixedReality-SpectatorView#345]
Is there a way to change the code to record the audio from the user camera listener? If the spectator camera is far away you can't hear any sound. Thank you!

**Comment by chrisfromwork** [comment]
no this is currently possible.

to be clear, are you asking that a mobile device records the user via the hololens microphone?

**Comment by jhurlbut** [comment]
I meant that I would like the spectator's scene's audio listener to be located at the user's camera position so that any spatialized audioclips would be heard from the point of view of the user and not the spectator. I think all that is needed is to deactivate the spectator camera's AudioListener component and add an AudioListener to a game object at the position of the user camera. Unfortunately, there appears to be a bug in iOS builds on Unity 2018 that removes spatial blending when you remove the AudioListener from the main camera. I also am not completely sure what the best way to find the position of the user camera is (on the spectator iOS app).
