### ISSUE TITLE
build Android on Unity 2019 err

### ISSUE THREAD

**Issue by tjsgtql** [microsoft/MixedReality-SpectatorView#348]
My project used unity 2019.1.14, so i create an empty project to test SpectatorView. i clone Repository,set environment. And build to Hololens, it worked. But,it error "**resource 'drawable/app_baner' not found in androidmanifest.xml:53**" when i build to Android.
i create another project by unity2018.3.14, everything is OK
Can someone tell me what could be the problem？

**Comment by chrisfromwork** [comment]
At first glance this doesn't necessarily seem related to spectator view. Do you have a custom android manifest declared in your project? If ASA created a manifest, it may be that you are needing some of the resources?

**Comment by diegohdezr** [comment]
I just followed the steps of the build 2019 demo, only loaded the arfoundation scene on the build and made sure the credentials of the azure spatial anchors were the same other than that everything should be the same

**Comment by shaketomo** [comment]
Hi, I had a same error.
I fix it by changing the settings in "**Prayer Settings**" -> "**Android**" -> "**Other Settings**" .
I checked the "**Auto Graphics API**" and "**Android TV compatibility**".

**Comment by tjsgtql** [comment]
> Hi, I had a same error.
> I fixed it by changing the settings in "**Prayer Settings**" -> "**Android**" -> "**Other Settings**" .
> I checked the "**Auto Graphics API**" and "**Android TV compatibility**".

thank you! It looks like this issue can be closed  (‾◡◝)  
Unfortunately I don’t have conditional verification now
