### ISSUE TITLE
can not Synchronize GameObject loaded through Instantiate

### ISSUE THREAD

**Issue by tjsgtql** [microsoft/MixedReality-SpectatorView#349]
i continuous Instantiate some GameObject like this: 

    public Transform parent;
    public string spherePath;
    Vector3 spanPo=Vector3 .one;
    Transform camTran;
    GameObject sphere;

    void Start()
    {
        camTran=Camera.main.transform;
        sphere=Resources.Load <GameObject >(spherePath);
        InvokeRepeating("Span",1,1);
    }

    void Span()
    {
        spanPo=camTran.position+camTran.forward -Vector3.down *0.2f;
        GameObject span=Instantiate(sphere,spanPo,Quaternion.identity,parent);
        // span .transform .SetParent (parent );
    }

i see many new sphere in player.but just one sphere in spectator.

**Comment by matthejo** [comment]
Are you using GameObjectHierarchyBroadcaster to enable broadcasting your GameObjects? Or have you checked this option to synchronize all GameObjects (from Spectator View -> Edit Settings)?

![image](https://user-images.githubusercontent.com/10050922/77475386-fbe87a80-6dd5-11ea-98fe-f9dfb7081761.png)

Your instantiated GameObjects need to either be descendants of a GameObject that has a GameObjectHierarchyBroadcaster (so the parent transform in this example), or you need to select "Automatically Broadcast All Game Objects" to broadcast everything.

**Comment by tjsgtql** [comment]
I did not select "Automatically Broadcast All Game Objects". 

But, the **first** descendants  GameObject is **synchronized**, **the latter is not.**

And, when an object is instantiated，I **already change the parent** to GameObjectHierarchyBroadcaster GameObject, the "parent" is it, in my code.

Maybe for other reasons？

**Comment by tjsgtql** [comment]
I republished the test and it seems to work fine. And **nothing changed**，i just republish at Hololens！Even the Android app is an old version
