### ISSUE TITLE
Version of Unity supported by the SpectatorView SDK

### ISSUE THREAD

**Issue by rdikshit** [microsoft/MixedReality-SpectatorView#371]
Hello Which version of Unity are supported by the SDK ? Based on the documentation I see that the samples are using Unity 2018.3.14f1 .
Are there other versions of UNITY supported?

**Comment by chrisfromwork** [comment]
Unity 2018.3.14f1 has been the version of unity used for all formal spectator view releases

Master is currently targetting Unity 2019.2.*. When Azure Spatial Anchors moves to support Unity 2019.3.*, we will update the spectator view codebase.
