### ISSUE TITLE
Failed to find single asset for vcruntime140_app.dll

### ISSUE THREAD

**Issue by linyanghuan** [microsoft/MixedReality-SpectatorView#372]
I want to film the hololens2 with kinect. I follow the "Getting started" step by step. Erverything is ok , I created the unity package.
![finishbuild](https://user-images.githubusercontent.com/23355395/81637116-2787f880-9448-11ea-9ddd-fe72c220fbdc.png)
I also use vs2019 build the dll file of kinect and copy to the package.
But when I import the package to example unity project it display 2 error:   

```
Failed to find single asset for vcruntime140_app.dll; found 0 instead!
UnityEngine.Debug:LogError(Object)
InitVCRTForwarders:.cctor() (at D:/github/MixedReality-SpectatorView/packages
/com.microsoft.mixedreality.spectatorview.0.0.1/SpectatorView.ExternalDependencies
/UnityFiles/Microsoft.VCRTForwarders.140.1.0.5/Editor/InitVCRTForwarders.cs:39)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes(Type[])
```

```
Failed to find single asset for vcruntime140_app.dll; found 0 instead!
UnityEngine.Debug:LogError(Object)
InitVCRTForwarders:.cctor() (at D:/github/MixedReality-SpectatorView/packages
/com.microsoft.mixedreality.spectatorview.0.0.1/SpectatorView.ExternalDependencies/
UnityFiles/Microsoft.VCRTForwarders.140.1.0.5/Editor/InitVCRTForwarders.cs:39)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes(Type[])
```

I click the "Spector View/Compositor" display error:  

```
DllNotFoundException: SpectatorView.Compositor.UnityPlugin
Microsoft.MixedReality.SpectatorView.CompositionManager.GetVideoFrameWidth () (at D:/github
/MixedReality-SpectatorView/packages/com.microsoft.mixedreality.spectatorview.0.0.1/SpectatorView
/Scripts/Compositor/CompositionManager.cs:414)
Microsoft.MixedReality.SpectatorView.Editor.CompositorWindowBase`1[TWindow].OnEnable () (at 
D:/github/MixedReality-SpectatorView/packages/com.microsoft.mixedreality.spectatorview.0.0.1
/SpectatorView.Editor/Scripts/CompositorWindowBase.cs:65)
Microsoft.MixedReality.SpectatorView.Editor.CompositorWindow.OnEnable () (at D:/github
/MixedReality-SpectatorView/packages/com.microsoft.mixedreality.spectatorview.0.0.1
/SpectatorView.Editor/Scripts/CompositorWindow.cs:54)
UnityEditor.EditorWindow:GetWindow(Type, Boolean, String, Boolean)
Microsoft.MixedReality.SpectatorView.Editor.EditorWindowBase`1:ShowWindow() (at D:/github
/MixedReality-SpectatorView/packages/com.microsoft.mixedreality.spectatorview.0.0.1
/SpectatorView.Editor/Scripts/EditorWindowBase.cs:59)
Microsoft.MixedReality.SpectatorView.Editor.CompositorWindow:ShowCompositorWindow() (at 
D:/github/MixedReality-SpectatorView/packages/com.microsoft.mixedreality.spectatorview.0.0.1
/SpectatorView.Editor/Scripts/CompositorWindow.cs:49)
```

I am sure all the dll file is in my package dir. 
I use Unity2019.2.5f1.

**Comment by chrisfromwork** [comment]
The first few errors related to vcruntime140_app.dll appear to be related to VCRTForwarders looking for dlls in the asset folder although we are placing dlls in a unity package.

The change here should remove these initializer scripts and prevent these issues from continuing to occur. You will need to recreate the Unity package for a clean repo:
https://github.com/microsoft/MixedReality-SpectatorView/pull/375

The second issue suggests that you did not compile the SpectatorView.Compositor.UnityPlugin dll or it is not included in your project. A few questions:

1. What device are you trying to use for azure kinect filming?
2. Did you run CreateUnityPackage.bat? If so, is there console output for the steps that copy the compiled native binaries to the SpectatorView.Native folder? It may be that these dlls have compiled correctly but that they weren't successfully added to  MixedReality-SpectatorView/packages/com.microsoft.mixedreality.spectatorview.0.0.1/SpectatorView.Native

The failure to locate the azure kinect sdks may also be resolved in the following review:
https://github.com/microsoft/MixedReality-SpectatorView/pull/375

**Comment by linyanghuan** [comment]
1. yes , I trying to use for azure kinect filming.
2. I run  CreateUnityPackage.bat and had copy the dll to the package. this is the console info:
```
Copying native plugins to SpectatorView.Unity
Copying DSLR compositor Release dlls to D:\github\MixedReality-SpectatorView\tools\Scripts\..\..\src\SpectatorView.Unity\Assets\SpectatorView.Native\Plugins\x64
Copying DSLR camera calibration dlls to D:\github\MixedReality-SpectatorView\tools\Scripts\..\..\src\SpectatorView.Unity\Assets\SpectatorView.Native\Plugins\x64
Copying ArUco marker detector dlls to D:\github\MixedReality-SpectatorView\tools\Scripts\..\..\src\SpectatorView.Unity\Assets\SpectatorView.Native\Plugins\WSA\x86
Copying empty ArUco marker detector dlls to D:\github\MixedReality-SpectatorView\tools\Scripts\..\..\src\SpectatorView.Unity\Assets\SpectatorView.Native\Plugins\WSA\ARM
Copying WinRTExtension dlls to D:\github\MixedReality-SpectatorView\tools\Scripts\..\..\src\SpectatorView.Unity\Assets\SpectatorView.Native\Plugins\WSA\x86
Copying WinRTExtension dlls to D:\github\MixedReality-SpectatorView\tools\Scripts\..\..\src\SpectatorView.Unity\Assets\SpectatorView.Native\Plugins\WSA\ARM
Looking for Azure Kinect SDK: C:\Program Files\Azure Kinect SDK v1.4.0
Copying Azure Kinect SDK dlls to D:\github\MixedReality-SpectatorView\tools\Scripts\..\..\src\SpectatorView.Unity\Assets\SpectatorView.Native\Plugins\x64
Looking for Azure Kinect Body Tracking SDK: C:\Program Files\Azure Kinect Body Tracking SDK
Copying Azure Kinect Body Tracking SDK dlls to D:\github\MixedReality-SpectatorView\tools\Scripts\..\..\src\SpectatorView.Unity\Assets\SpectatorView.Native\Plugins\x64
Copying .meta files                                                                                                                             
```

**Comment by chrisfromwork** [comment]
This output suggests that you compiled the native binaries correctly and that they have been successfully added to your unity project. Are you having issues filming?

**Comment by linyanghuan** [comment]
I still have the 2 error.  I do not konw what i miss, I'm going crazy.

**Comment by linyanghuan** [comment]
I will restart again use new repo.

**Comment by linyanghuan** [comment]
I still have error ：
```
DllNotFoundException: SpectatorView.Compositor.UnityPlugin
Microsoft.MixedReality.SpectatorView.CompositionManager.GetVideoFrameWidth () (at D:/github
/MixedReality-SpectatorView/packages/com.microsoft.mixedreality.spectatorview.0.0.1/SpectatorView
/Scripts/Compositor/CompositionManager.cs:414)
Microsoft.MixedReality.SpectatorView.Editor.CompositorWindowBase`1[TWindow].OnEnable () (at 
D:/github/MixedReality-SpectatorView/packages/com.microsoft.mixedreality.spectatorview.0.0.1
/SpectatorView.Editor/Scripts/CompositorWindowBase.cs:65)
Microsoft.MixedReality.SpectatorView.Editor.CompositorWindow.OnEnable () (at D:/github
/MixedReality-SpectatorView/packages/com.microsoft.mixedreality.spectatorview.0.0.1
/SpectatorView.Editor/Scripts/CompositorWindow.cs:54)
UnityEditor.EditorWindow:GetWindow(Type, Boolean, String, Boolean)
Microsoft.MixedReality.SpectatorView.Editor.EditorWindowBase`1:ShowWindow() (at D:/github
/MixedReality-SpectatorView/packages/com.microsoft.mixedreality.spectatorview.0.0.1
/SpectatorView.Editor/Scripts/EditorWindowBase.cs:59)
Microsoft.MixedReality.SpectatorView.Editor.CompositorWindow:ShowCompositorWindow() (at 
D:/github/MixedReality-SpectatorView/packages/com.microsoft.mixedreality.spectatorview.0.0.1
/SpectatorView.Editor/Scripts/CompositorWindow.cs:49)
```
I am sure I have the SpectatorView.Compositor.UnityPlugin.dll in path :
```D:\github\MixedReality-SpectatorView\packages\com.microsoft.mixedreality.spectatorview.0.0.1\SpectatorView.Native\Plugins\x64```

**Comment by linyanghuan** [comment]
I chang the `SpectatorView.Compositor.UnityPlugin.dll` to a shot name `SVCU.dll` and then change the script . it is work, no error.

**Comment by klasaf** [comment]
> I still have error ：
> 
> ```
> DllNotFoundException: SpectatorView.Compositor.UnityPlugin
> Microsoft.MixedReality.SpectatorView.CompositionManager.GetVideoFrameWidth () (at D:/github
> /MixedReality-SpectatorView/packages/com.microsoft.mixedreality.spectatorview.0.0.1/SpectatorView
> /Scripts/Compositor/CompositionManager.cs:414)
> Microsoft.MixedReality.SpectatorView.Editor.CompositorWindowBase`1[TWindow].OnEnable () (at 
> D:/github/MixedReality-SpectatorView/packages/com.microsoft.mixedreality.spectatorview.0.0.1
> /SpectatorView.Editor/Scripts/CompositorWindowBase.cs:65)
> Microsoft.MixedReality.SpectatorView.Editor.CompositorWindow.OnEnable () (at D:/github
> /MixedReality-SpectatorView/packages/com.microsoft.mixedreality.spectatorview.0.0.1
> /SpectatorView.Editor/Scripts/CompositorWindow.cs:54)
> UnityEditor.EditorWindow:GetWindow(Type, Boolean, String, Boolean)
> Microsoft.MixedReality.SpectatorView.Editor.EditorWindowBase`1:ShowWindow() (at D:/github
> /MixedReality-SpectatorView/packages/com.microsoft.mixedreality.spectatorview.0.0.1
> /SpectatorView.Editor/Scripts/EditorWindowBase.cs:59)
> Microsoft.MixedReality.SpectatorView.Editor.CompositorWindow:ShowCompositorWindow() (at 
> D:/github/MixedReality-SpectatorView/packages/com.microsoft.mixedreality.spectatorview.0.0.1
> /SpectatorView.Editor/Scripts/CompositorWindow.cs:49)
> ```
> 
> I am sure I have the SpectatorView.Compositor.UnityPlugin.dll in path :
> `D:\github\MixedReality-SpectatorView\packages\com.microsoft.mixedreality.spectatorview.0.0.1\SpectatorView.Native\Plugins\x64`

I had the same issue when opening the Compositor Window in the editor. I don't know why but the solution proposed by @linyanghuan worked for me. Thanks!
