### ISSUE TITLE
Pre-Built package for Spectator View

### ISSUE THREAD

**Issue by rdikshit** [microsoft/MixedReality-SpectatorView#373]
Hello.
Is there a pre-build package that you could provide for the Master branch (2019.2.x version of unity ) or even for the final release version ?

I have been following the steps documented , and am running into numerous issues which I have not been able to resolve. 

If there is a pre-build package , we will save a lot of time and effort .

Thank you

**Comment by chrisfromwork** [comment]
No this does not currently exist
