### ISSUE TITLE
open SpectatorView.Example.Unity error

### ISSUE THREAD

**Issue by tianliang0314** [microsoft/MixedReality-SpectatorView#378]

**Comment by tianliang0314** [comment]
when i open the sample project,there are 2 errors

> Failed to set DLL directory E:\MixedReality-SpectatorView\samples\SpectatorView.Example.Unity\Packages\com.microsoft.mixedreality.spectatorview\SpectatorView.ExternalDependencies\UnityFiles\Microsoft.VCRTForwarders.140.1.0.5\x64: Win32 error 3
UnityEngine.Debug:LogError(Object)
InitVCRTForwarders:.cctor() (at E:/MixedReality-SpectatorView/src/SpectatorView.Unity/Assets/SpectatorView.ExternalDependencies/UnityFiles/Microsoft.VCRTForwarders.140.1.0.5/Editor/InitVCRTForwarders.cs:49)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes(Type[]) (at D:/unity/Editor/Mono/EditorAssemblies.cs:108)

> Failed to set DLL directory E:\MixedReality-SpectatorView\samples\SpectatorView.Example.Unity\Packages\com.microsoft.mixedreality.spectatorview\SpectatorView.ExternalDependencies\UnityFiles\Microsoft.MixedReality.QR.0.5.2100\x64: Win32 error 3
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.QR.Init:.cctor() (at E:/MixedReality-SpectatorView/src/SpectatorView.Unity/Assets/SpectatorView.ExternalDependencies/UnityFiles/Microsoft.MixedReality.QR.0.5.2100/Editor/Microsoft.MixedReality.QR.Init.cs:57)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes(Type[]) (at D:/unity/Editor/Mono/EditorAssemblies.cs:108)

![image](https://user-images.githubusercontent.com/13743806/82623378-9fa5a980-9c12-11ea-817f-748dae7acbc2.png)

i can clear it and build the sample to hololens,but the application in the hololens shows window style
![image](https://user-images.githubusercontent.com/13743806/82623694-53a73480-9c13-11ea-80c3-d666a94665e1.png)
the build settings are correct, but i dont konw how to fix it?

**Comment by linyanghuan** [comment]
好像删掉那两个报错的cs文件就行，#375里面的第三点有提到

**Comment by linyanghuan** [comment]
出现窗口是你的unity项目没有设置混合现实的插件，你仔细看看官方文档就行

**Comment by tianliang0314** [comment]
@linyanghuan 我觉得奇怪得点是我XR Setting 里都设置了得
![image](https://user-images.githubusercontent.com/13743806/82625704-7556ea80-9c18-11ea-8a48-2c15ca48e5e8.png)

**Comment by linyanghuan** [comment]
那就不清楚了，官方做的unity项目都怪怪的
