### ISSUE TITLE
demo 2019 build failed

### ISSUE THREAD

**Issue by diegohdezr** [microsoft/MixedReality-SpectatorView#390]
I tried to build the 2019 demo with unity 2019.2.19f1 and it tells me the build failed because: UnityCompositorInterface' does not exist in the current context, I tried both by using the build setings -> build to generate a VS solution and the mrtk build window to generate an appx and both failed, tried it for ARM and ARM 64 with no susccess

**Comment by chrisfromwork** [comment]
A fix went in for this yesterday:
https://github.com/microsoft/MixedReality-SpectatorView/pull/389

You may need to pull the most recent master to pick up the change.

Please reopen this issue if you still experience problems after getting commits in the above pull request. :)
