### ISSUE TITLE
Can't enable QR code detection 

### ISSUE THREAD

**Issue by v2morrow** [microsoft/MixedReality-SpectatorView#391]
I am testing the SpectatorView.Example.Unity scene and trying to connect my HL2 and android phone. I enter IP address and my phone shows a qr code but my Hololens does't show anything new. It can't detect the qr code and never ask for camera permission.  When I close the app in hololens, qr code is closed on my phone and back to 'enter ip address' window.
I tried others app and the qr code detection worked correctly. 

Did I miss something?

**Comment by chrisfromwork** [comment]
if you open your settings application on your HoloLens 2 and look at app permissions, does SpectatorView.Example.Unity have camera permissions enabled? If not, I would suggest attaching a debugger to the QRCodeMarkerDetector script to see what happens when starting qr code detection/calling qr code capability dialogues.

**Comment by v2morrow** [comment]
App camera permission is not enable.  I check the "debug logging" but it doesn't show anything in unity console
![image](https://user-images.githubusercontent.com/38543069/84887828-ec24bd80-b0c8-11ea-8f73-c784b487a8a5.png)

**Comment by chrisfromwork** [comment]
If you enable the camera permission for the application in your settings, you may be able to get past the problem.

This is the line that should be executing when starting up the qr code marker detector:
https://github.com/microsoft/MixedReality-SpectatorView/blob/7796da6acb0ae41bed1b9e0e9d1c5c683b4b8374/src/SpectatorView.Unity/Assets/SpectatorView/Scripts/MarkerDetection/QRCode/QRCodesManager.cs#L230

I'm not sure if this permission request will execute more than once after installing the application. You may need to reinstall the application on your hololens for the dialogue to reappear.

**Comment by v2morrow** [comment]
The firts time I run my app on HL2 it ask for camera permission but QR code detection doesn't work. After restart my app it works permanently. 
Does the status not refresh at the first time?
