### ISSUE TITLE
advapi32 could not be loaded at runtime

### ISSUE THREAD

**Issue by diegohdezr** [microsoft/MixedReality-SpectatorView#394]
Hello! I've compiled the build2019 demo in android and added a log to the scene, because it was not displaying the content even when the hololens client recognized another device was connecting to the session, the log threw an error saying that advapi32 could not be loaded, I am attaching a screenshot
I am using a redmi note 8 for this with android version: 9 PKQ1.190616.001

![Screenshot_2020-06-14-20-21-22-566_com Microsoft SpectatorView Build2019Demo](https://user-images.githubusercontent.com/12818626/84611194-b42c3900-ae82-11ea-916f-17db7049d119.jpg)

**Comment by diegohdezr** [comment]
![image](https://user-images.githubusercontent.com/12818626/84681317-8c2bec80-aef9-11ea-84d7-6e4b4ccda9e4.png)
 I got this from the android logcat for unity, it breaks when trying to use concurrent collections it seems, 
similar error advices to upgrade to 2019.3.9: https://forum.unity.com/threads/libadvapi32.828759/

but this project is not compatible, any workarround?

**Comment by chrisfromwork** [comment]
What Unity version did you use to compile the Android application?

**Comment by diegohdezr** [comment]
2019.2.19
![image](https://user-images.githubusercontent.com/12818626/84712052-51dc4280-af2d-11ea-9ce6-31b22799bdf8.png)

**Comment by diegohdezr** [comment]
https://forum.unity.com/threads/libadvapi32.828759/ in that answer the unity guys says that it is just a warning with no effect whatsoever I did further testing and the app works as it should if more of the environment is scanned before connecting to the session, so the warning is still there but causes no effect, should the thread be closed?

**Comment by chrisfromwork** [comment]
Are you unblocked? If so I am in favor of closing this issue.

**Comment by diegohdezr** [comment]
It does not block me anymore, it is just a warning that is suposed to be solved when upgrading to 2019.3.9 or later, so I am closing the issue. thanks!
