### ISSUE TITLE
Magic number

### ISSUE THREAD

**Issue by Johnzdh** [microsoft/MixedReality-SpectatorView#397]
I find there is a magic number in the MixedReality-SpectatorView/src/HolographicCamera.Unity/Assets/HolographicCamera/Scripts/CalibrationDataProvider.cs.
` position += new Vector3(0f, 0.08f, 0.08f);`
Could anyone explain it?

**Comment by chrisfromwork** [comment]
I don't think there is a great explanation for this number. When folks tested out the camera rig internally they determined that the underlying winrt HMD HoloLens transform had this offset when compared to the HMD unity camera transform. Without this transform, error is introduced by using the winrt HMD HoloLens transform for camera pose reporting. Thus we add this offset here when sending calibration data for the camera rig.
