### ISSUE TITLE
QR code not showing

### ISSUE THREAD

**Issue by Wenlong0913** [microsoft/MixedReality-SpectatorView#400]
Project: SpectatorView.Example.Unity
commit: f8c85f8 (tag v1.1.0)
Device: Hololens2 and an Android mobile (os: android 10)
Unity version: 2019.2.12f1
VS version: 2019 community edition

Hi, to whom it may concern,

Many thanks for the great project. 

We are trying to test sample project `SpectatorView.Example.Unity` on Hololens 2 with an android phone. The related apps had been installed on Hololens and Android phone successfully. Hololens is the host and android is the spectator.
However, after I input the IP address of hololens and press launch button on android, the QR code didn't show. Please look at the attached screenshot.

 ![sv](https://user-images.githubusercontent.com/17941167/86243799-8c0a3d00-bbd9-11ea-931a-35ea8c968042.jpg) Fron hololens, at the same location, a sphere and a cube can be viewed.

Can anyone please give some suggestions about how to fix this? Any suggestions will be greatly appreciated.

**Comment by Wenlong0913** [comment]
I'm pretty sure the hololens and mobile are under the same wifi environment.

**Comment by Wenlong0913** [comment]
![sc](https://user-images.githubusercontent.com/17941167/86344679-21b2d480-bc8d-11ea-892c-18fa6b857a86.png)
Unity logs showed that they were not connected. I'm sure the IP address is correct because the hololens was deployed by using the same IP.

**Comment by Wenlong0913** [comment]
I found that I can't ping the hololens ip address but  visual studio can deploy software to that ip via remote machine.
I've already opened the developer option on hololens 2, is there any other configurations I have to change?

**Comment by Wenlong0913** [comment]
Hi, I've resolved this issue.
The main reason is exactly the as issue [385](https://github.com/microsoft/MixedReality-SpectatorView/issues/385)

**Comment by pieper1000** [comment]
Hi Wenlong0913, 

I hope you are doing fine!
This message is a little out of place, but I couldn't find any other way of reaching you than here.
I hope it is alright that I'm messaging you here.
I'm currently trying to build my own seafile server, but I'm getting the same error as you have gotten
here https://www.qdxingtu.com/key/compile%20failed.html .
You seem to have solved the problem yourself, but with my complete lack of C knowledge I'm not getting around
it. 
Do you still know how you solved the issue?

Thank you very much!
Kind Regards
