### ISSUE TITLE
missing script file

### ISSUE THREAD

**Issue by Septillion** [microsoft/MixedReality-SpectatorView#413]
In the doc describing setting the project up, it said:

- On Mac or Linux, you can run /tools/scripts/SetupRepository.sh

whereas the file doesn't exist in the directory.

**Comment by chrisfromwork** [comment]
This is stale documentation. Its now suggested to use powershell for mac:
https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-macos?view=powershell-7
