### ISSUE TITLE
Update Samples to ARFoundation

### ISSUE THREAD

**Issue by andreiborodin** [microsoft/MixedReality-SpectatorView#43]
ARKit will no longer be offered as a standalone SDK, in the future it will be offered through ARFoundation. This is most likely true for ARCore some time soon.

Once this happens, and ASA is updated to use ARFoundation, we need to migrate our symbols.

**Comment by chrisfromwork** [comment]
We should add a note that ARFoundation is not currently supported in our documentation.

**Comment by chrisfromwork** [comment]
We will need ASA to support ARFoundation prior to making this change.

**Comment by chrisfromwork** [comment]
We are now using ARFoundation in master for Android and iOS
