### ISSUE TITLE
Difficulty With Understanding Spatial Alignment

### ISSUE THREAD

**Issue by methot-ilya-3ds** [microsoft/MixedReality-SpectatorView#440]
In my current setup I am able to sync both the IOS device and the Hololens device so they are both displaying the correct objects and tacking my hand movement as well.

The problem is that there does not be a solution to sync the world space for both the Hololens and the IOS device. 

Often the two scenes will be mismatched, or entirely different rotations. The only (temporary) solution I've encountered is to make sure that I have the IOS device at the same starting location as the Hololens.

I have not seen any documentation on how to "center" the IOS and the Hololens device once they are both connected.

**Comment by estherlxd** [comment]
Hi, I am facing the same issue, did you solve it? Would you mind sharing your solution?
