### ISSUE TITLE
CreateUnityPackage.bat not building the package. Building errors for tiff:x86_uwp library

### ISSUE THREAD

**Issue by KleyosMajere** [microsoft/MixedReality-SpectatorView#463]
Here is the log of the operations made by the CreateUnityPackage.bat script. Errors with the building of tiff:x86_uwp.

> Building package tiff[core,jpeg,lzma,zip]:x86-uwp...
> -- Using community triplet x86-uwp. This triplet configuration is not guaranteed to succeed.
> -- [COMMUNITY] Loading triplet configuration from: D:\Git\unity-test-apps\sv\external\vcpkg\triplets\community\x86-uwp.cmake
> -- Downloading https://gitlab.com/libtiff/libtiff/-/archive/v4.3.0/libtiff-v4.3.0.tar.gz -> libtiff-libtiff-v4.3.0.tar.gz...
> -- Extracting source D:/Git/unity-test-apps/sv/external/vcpkg/downloads/libtiff-libtiff-v4.3.0.tar.gz
> -- Applying patch cmakelists.patch
> -- Applying patch fix-pkgconfig.patch
> -- Applying patch FindCMath.patch
> -- Using source at D:/Git/unity-test-apps/sv/external/vcpkg/buildtrees/tiff/src/v4.3.0-d820bbde31.clean
> -- Configuring x86-uwp
> -- Building x86-uwp-dbg
> CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
>     Command failed: D:/Git/unity-test-apps/sv/external/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
>     Working Directory: D:/Git/unity-test-apps/sv/external/vcpkg/buildtrees/tiff/x86-uwp-dbg
>     See logs for more information:
>       D:\Git\unity-test-apps\sv\external\vcpkg\buildtrees\tiff\install-x86-uwp-dbg-out.log
> 
> Call Stack (most recent call first):
>   installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
>   installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
>   ports/tiff/portfile.cmake:48 (vcpkg_cmake_install)
>   scripts/ports.cmake:145 (include)
> 
> Error: Building package tiff:x86-uwp failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
> Then check for known issues at:
>   https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+tiff
> You can submit a new issue at:
>   https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[tiff]+Build+error
> including:
>   package: tiff[core,jpeg,lzma,zip]:x86-uwp -> 4.3.0#6
>     vcpkg-tool version: 2022-03-25-d9702d9d89b9468c32efc3f18fb84c3021d7dbae
>     vcpkg-scripts version: 54951282f 2022-03-30 (2 hours ago)
> 
> Additionally, attach any relevant sections from the log files above.

Here is also the logfile of vcpkg with the errors during the installation process: [install-x86-uwp-dbg-out.log](https://github.com/microsoft/MixedReality-SpectatorView/files/8384910/install-x86-uwp-dbg-out.log)

**Comment by ChristopherRemde** [comment]
Hey, I wrote a guide on how to fix this issue here: #464

**Comment by KleyosMajere** [comment]
Hi @ChristopherRemde. Finally i tested your guide writed on issue [#464](https://github.com/microsoft/MixedReality-SpectatorView/issues/464) and i being able to building the SpectatorView package with all the external dependencies and patching the TIFF UWP library. Thanks for your help, it was really appreciated!
